# Generated by Django 2.2.4 on 2022-02-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USER',
        ),
    ]
