# Generated by Django 2.2.4 on 2022-02-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_comment_massage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manyusers', models.ManyToManyField(related_name='manybooks', to='login_app.USER')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='login_app.USER')),
            ],
        ),
        migrations.RemoveField(
            model_name='massage',
            name='users',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Massage',
        ),
    ]
